### ISSUE TITLE
mongodb queries design checklist (6*day)

### ISSUE THREAD

**Issue by plopezgit** [plopezgit/Sprint2_T4_MongoDB_Query#1]
- [x] Escriba una consulta para mostrar todos los documentos de la colección Restaurantes.
`db.restaurante.find();`
- [x] Escriba una consulta para mostrar el ID del restaurante, el nombre, la ciudad y la cocina de todos los documentos de la colección Restaurantes.
`db.restaurant.find({},{restaurant_id: 1, name: 1, borough: 1, cuisine: 1});`
- [x] Escriba una consulta para mostrar el restaurante_id, el nombre, la ciudad y la cocina, pero excluya el campo _id para todos los documentos de la colección Restaurantes.
`db.restaurant.find({},{_id: 0, restaurant_id: 1, name: 1, borough: 1, cuisine: 1});`
- [x] Escriba una consulta para mostrar restaurante_id, nombre, ciudad y código postal, pero excluya el campo _id para todos los documentos de la colección Restaurantes.
`db.restaurant.find({},{_id: 0, address: {zipcode: 1}, restaurant_id: 1, name: 1, borough: 1, cuisine: 1});`
- [x] Escribe una consulta para mostrar todos los restaurantes que hay en el Bronx.
`db.restaurant.find({borough: "Bronx"},{_id: 0, restaurant_id: 1, name: 1, borough: 1});`
- [x] Escribe una consulta para mostrar los primeros 5 restaurantes que hay en el Bronx.
`db.restaurant.find().limit(5);`
- [x] Ingrese una consulta para mostrar los siguientes 5 restaurantes después de omitir los primeros 5 en el Bronx.
`db.restaurant.find({},{_id: 0, restaurant_id: 1}).skip(5).limit(5);`
- [x] Escribe una consulta para encontrar los restaurantes que tienen una puntuación superior a 90.
`db.restaurant.find({ 'grades.score': {$gt: 90}}, {_id: 0, restaurant_id: 1, grades: {score: 1}});`
- [x] Escriba una consulta para encontrar restaurantes que tengan una puntuación superior a 80 pero inferior a 100.
`db.restaurant.find({$and: [ { 'grades.score': {$gt: 90}}, { 'grades.score': {$lt: 100}} ]}, {_id: 0, restaurant_id: 1, grades: {score: 1}});`
`db.restaurant.find({ 'grades.score': {$gt: "90", $lt: "100"}}, {_id: 0, restaurant_id: 1, grades: {score: 1}});`
- [x] Escriba una consulta para encontrar restaurantes que estén ubicados en un valor de latitud menor que -95.754168.
`db.restaurant.find({ 'address.coord': {$lt: -95.754168}}, {_id: 0, restaurant_id: 1, address: {coord: 1}});`
- [x] Escriba una consulta MongoDB para encontrar restaurantes que no sirvan cocina "estadounidense" y tengan una calificación superior a 70 y una longitud inferior a -65.754168.
`db.restaurant.find({$and: [ {cuisine: {'$regex' : '^((?!American).)*$', '$options' : 'i'} }, { 'grades.score': {$gt: 70}}, {'address.coord': {$lt: -65.754168}}]}, {_id: 0, restaurant_id: 1, cuisine: 1, grades: {score: 1}});`
- [x] Escriba una consulta para encontrar los restaurantes que no preparan cocina 'americana' y obtuvieron un marcador superior a 70 y están ubicados en una longitud inferior a -65,754168. Nota: Realice esta consulta sin utilizar el operador $and.
`db.restaurant.find( { 'grades.score': {$gt: 70}, 'address.coord': {$lt: -65.754168}, cuisine: {'$regex' : '^((?!American).)*$', '$options' : 'i'}  } , {_id: 0, restaurant_id: 1, grades: {score: 1}});`
- [x] Ingrese una consulta para encontrar restaurantes que no sirvan cocina "estadounidense" y recibieron una calificación de "A" que no pertenece a Brooklyn. El documento deberá visualizarse según la cocina en orden descendente.
`db.restaurant.find({ cuisine: {'$regex' : '^((?!American).)*$', '$options' : 'i'}, 'grades.grade': "A", borough: {'$regex' : '^((?!Brooklyn).)*$', '$options' : 'i'}   },{_id: 0, restaurant_id: 1, name: 1});`
- [x] Escriba una consulta para encontrar el ID del restaurante, el nombre, la ciudad y la cocina de aquellos restaurantes que contienen 'Wil' como las primeras tres letras de su nombre.
`db.restaurant.find({ 'name': {'$regex' : '^Wil', '$options' : 'i'}}, {_id: 0, restaurant_id: 1, name: 1, borough: 1, cuisine: 1 });`
- [x] Escriba una consulta para encontrar el ID del restaurante, el nombre, la ciudad y la cocina de aquellos restaurantes que contengan 'ces' como las últimas tres letras de su nombre.
`db.restaurant.find({ 'name': {'$regex' : 'ces$', '$options' : 'i'}}, {_id: 0, restaurant_id: 1,  name: 1, borough: 1, cuisine: 1 });`
- [x] Escriba una consulta para encontrar el ID del restaurante, el nombre, la ciudad y la cocina de aquellos restaurantes que contienen 'Reg' como tres letras en algún lugar de su nombre.
`db.restaurant.find({ 'name': {'$regex' : 'Reg', '$options' : 'i'}}, {_id: 0, restaurant_id: 1,  name: 1, borough: 1, cuisine: 1 });`
- [ ] Escribe una consulta para encontrar restaurantes que pertenezcan al Bronx y preparen cualquier plato americano o chino.

- [x] Escriba una consulta para encontrar el ID del restaurante, el nombre, la ciudad y la cocina de aquellos restaurantes que pertenecen a Staten Island, Queens, Bronx o Brooklyn.
`db.restaurant.find({$or: [ {borough: "Staten Island"}, {borough: "Queens"}, {borough: "Bronx"}, {borough: "Brooklyn"} ] },{_id: 0, restaurant_id: 1, name: 1, borough: 1, cuisine: 1 });`
- [ ] Escriba una consulta para encontrar el ID del restaurante, el nombre, la ciudad y la cocina de aquellos restaurantes que no están en Staten Island, Queens, Bronx o Brooklyn.

- [x] Escriba una consulta para encontrar el ID del restaurante, el nombre, la ciudad y la cocina de aquellos restaurantes que obtengan una puntuación no superior a 10.
`db.restaurant.find({'grades.score': {$lte:10}}, {_id: 0, restaurant_id: 1, name: 1, borough: 1, cuisine: 1 });`
- [ ] Escriba una consulta para encontrar el ID del restaurante, el nombre, la ciudad y la cocina de aquellos restaurantes que preparan pescado excepto "americano" y "chino" o el nombre del restaurante comienza con las letras "Wil".

- [ ] Escriba una consulta para encontrar el restaurante_id, el nombre y las calificaciones de aquellos restaurantes que logran una calificación "A" y una puntuación de 11 en los datos del estudio ISODate "2014-08-11T00:00:00Z".

- [ ] Escriba una consulta para encontrar el ID del restaurante, el nombre y las calificaciones de aquellos restaurantes donde el elemento de matriz de segundo grado contiene una calificación de "A" y un marcador 9 en una fecha ISO "2014-08-11T00:00:00Z".

- [ ] Escriba una consulta para encontrar el restaurante_id, nombre, dirección y ubicación geográfica de aquellos restaurantes donde el segundo elemento de la matriz de coordenadas contenga un valor mayor que 42 y hasta 52.

- [x] Escriba una consulta para organizar el nombre del restaurante en orden ascendente junto con todas las columnas.
`db.restaurant.find(). sort({"name": 1});`
- [x] Escriba una consulta para organizar el nombre del restaurante en orden descendente junto con todas las columnas.
`db.restaurant.find(). sort({"name": -1});`
- [ ] Escribe una consulta para organizar el nombre de la cocina en orden ascendente y por el mismo distrito gastronómico. orden descendiente

- [ ] Escribe una consulta para conocer todas las direcciones que no contienen la calle.

- [ ] Escriba una consulta que seleccione todos los documentos de la colección de restaurantes donde el valor del campo coord sea Doble.

- [ ] Escriba una consulta que seleccione el restaurante_id, el nombre y la calificación para aquellos restaurantes que devuelvan 0 como resto después de dividir la puntuación por 7.

- [x] Escriba una consulta para encontrar el nombre del restaurante, la ciudad, la longitud y la altitud y cocine para aquellos restaurantes que contengan 'mon' como tres letras en algún lugar de su nombre.
`db.restaurant.find({ 'name': {'$regex' : 'mon', '$options' : 'i'}}, {_id: 0, name: 1, cuisine: 1, borough: 1, address: {coord: 1}  });`
- [x] Escriba una consulta para encontrar el nombre del restaurante, la ciudad, la longitud y la latitud y cocine para aquellos restaurantes que contengan 'Mad' como las primeras tres letras de su nombre.
`db.restaurant.find({ 'name': {'$regex' : '^Mad', '$options' : 'i'}}, {_id: 0, name: 1, cuisine: 1, borough: 1, address: {coord: 1}  });`
